#!/bin/sh
set -eu

port=${1:?usage: phttp PORT [http-server options]}
shift

address=$(
	ip -4 -o address show dev tailscale0 |
		awk '{ sub(/\/.*/, "", $4); print $4; exit }'
)

if [ -z "$address" ]; then
	echo "phttp: tailscale0 has no IPv4 address" >&2
	exit 1
fi

exec http-server "$@" \
	--address "$address" \
	--port "$port" \
	--log-ip \
	--robots
